# Generated by Django 2.1.5 on 2019-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='correct_keys',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='speed',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='wrong_keys',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
