# Generated by Django 2.1.5 on 2019-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_provider', '0002_auto_20191018_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
